collections:
  - name: community.general
    version: "11.4.0"
  - name: ansible.posix
    version: "2.1.0"

roles:
  # TODO (https://galaxy.ansible.com/ui/repo/published/arpanrec/nebula/content/role/gnome)
  - name: jaredhocutt.gnome_extensions
    src: https://github.com/jaredhocutt/ansible-gnome-extensions
    version: "0b8a556"
